export const fetchSorteos = async () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve([
        {
          id: 1,
          nombre: "Xbox 360",
          precio: 20,
          imagen:
            "https://www.pngkit.com/png/full/224-2241739_xbox-360-console.png",
          premio: "Xbox 360",
          cantidadMaximaBoletos: 150,
          fechaInicialVentaBoletos: "2025-12-04",
          fechaFinalVentaBoletos: "2025-12-23",
          estado: "activo",
          fechaCreacion: "2025-12-03",
          limiteAparadoPersona: 15,
          descripcion: "Consola de videojuegos Xbox 360 en excelente estado.",
        },
        {
          id: 2,
          nombre: "Despensa",
          precio: 15,
          imagen:
            "https://despensatotal.com/images/uploads/despensa-completa.jpg",
          premio: "Despensa con víveres esenciales",
          cantidadMaximaBoletos: 250,
          fechaInicialVentaBoletos: "2025-12-01",
          fechaFinalVentaBoletos: "2025-12-18",
          estado: "activo",
          fechaCreacion: "2025-11-28",
          limiteAparadoPersona: 20,
          descripcion: "Una despensa completa con productos de canasta básica.",
        },
        {
          id: 3,
          nombre: "Útiles escolares",
          precio: 30,
          imagen:
            "https://e7.pngegg.com/pngimages/820/199/png-clipart-encapsulated-postscript-school-supplies-school-material-preview.png",
          premio: "Paquete de útiles escolares",
          cantidadMaximaBoletos: 100,
          fechaInicialVentaBoletos: "2025-12-10",
          fechaFinalVentaBoletos: "2025-12-28",
          estado: "activo",
          fechaCreacion: "2025-12-08",
          limiteAparadoPersona: 10,
          descripcion:
            "Kit con cuadernos, lápices, colores y más, ideal para el regreso a clases.",
        },
        {
          id: 4,
          nombre: "Smartwatch Deportivo",
          precio: 45,
          imagen: "https://png.pngtree.com/png-clipart/20250301/original/pngtree-black-smartwatch-modern-fitness-tracker-with-digital-display-png-image_20545116.png",
          premio: "Reloj inteligente con GPS",
          cantidadMaximaBoletos: 80,
          fechaInicialVentaBoletos: "2025-11-15",
          fechaFinalVentaBoletos: "2025-12-05",
          estado: "activo",
          fechaCreacion: "2025-11-10",
          limiteAparadoPersona: 8,
          descripcion:
            "Smartwatch resistente al agua con monitor de ritmo cardíaco y contador de pasos.",
        },
        {
          id: 5,
          nombre: "Bicicleta de Montaña",
          precio: 80,
          imagen: "[IMAGEN_ID_5]",
          premio: "Bicicleta rodada 29",
          cantidadMaximaBoletos: 60,
          fechaInicialVentaBoletos: "2025-12-01",
          fechaFinalVentaBoletos: "2025-12-25",
          estado: "inactivo",
          fechaCreacion: "2025-11-20",
          limiteAparadoPersona: 5,
          descripcion:
            "Bicicleta de montaña con suspensión delantera y 21 velocidades.",
        },
        {
          id: 6,
          nombre: "Audífonos Inalámbricos",
          precio: 25,
          imagen: "[IMAGEN_ID_6]",
          premio: "Auriculares Bluetooth de alta fidelidad",
          cantidadMaximaBoletos: 200,
          fechaInicialVentaBoletos: "2025-11-01",
          fechaFinalVentaBoletos: "2025-11-30",
          estado: "finalizado",
          fechaCreacion: "2025-10-25",
          limiteAparadoPersona: 25,
          descripcion: "Audífonos con cancelación de ruido y estuche de carga.",
        },
        {
          id: 7,
          nombre: "Tarjeta de Regalo Amazon",
          precio: 10,
          imagen: "https://tse2.mm.bing.net/th/id/OIP.Dwf3tETZVj5TJbMgofaYHwHaFN?rs=1&pid=ImgDetMain&o=7&rm=3",
          premio: "Crédito de $100 USD en Amazon",
          cantidadMaximaBoletos: 350,
          fechaInicialVentaBoletos: "2025-12-15",
          fechaFinalVentaBoletos: "2026-01-05",
          estado: "activo",
          fechaCreacion: "2025-12-12",
          limiteAparadoPersona: 30,
          descripcion:
            "Tarjeta de regalo digital válida para compras en Amazon.",
        },
        {
          id: 8,
          nombre: "Cafetera Programable",
          precio: 35,
          imagen: "https://th.bing.com/th/id/R.5bff41fd5b69e3419ac9fffd205c84bb?rik=lCj3o339qylGgA&pid=ImgRaw&r=0",
          premio: "Máquina de café de goteo",
          cantidadMaximaBoletos: 95,
          fechaInicialVentaBoletos: "2025-11-20",
          fechaFinalVentaBoletos: "2025-12-10",
          estado: "activo",
          fechaCreacion: "2025-11-18",
          limiteAparadoPersona: 12,
          descripcion: "Cafetera con temporizador y capacidad para 12 tazas.",
        },
        {
          id: 9,
          nombre: "Kit de Herramientas",
          precio: 40,
          imagen: "[IMAGEN_ID_9]",
          premio: "Juego completo de herramientas para el hogar",
          cantidadMaximaBoletos: 120,
          fechaInicialVentaBoletos: "2025-10-01",
          fechaFinalVentaBoletos: "2025-10-31",
          estado: "finalizado",
          fechaCreacion: "2025-09-25",
          limiteAparadoPersona: 10,
          descripcion:
            "Estuche con martillo, destornilladores, llaves y pinzas.",
        },
        {
          id: 10,
          nombre: "Drone con Cámara HD",
          precio: 65,
          imagen: "https://th.bing.com/th/id/R.4acae882ab5f87c153d117336c6cbc6b?rik=OVQVM2o%2bIFdPWg&pid=ImgRaw&r=0",
          premio: "Dron plegable con grabación de video",
          cantidadMaximaBoletos: 70,
          fechaInicialVentaBoletos: "2025-12-08",
          fechaFinalVentaBoletos: "2025-12-30",
          estado: "activo",
          fechaCreacion: "2025-12-05",
          limiteAparadoPersona: 7,
          descripcion:
            "Drone compacto con cámara de alta definición y retorno automático.",
        },
      ]);
    }, 100);
  });
};
